let Lessons = [
    { id: 1001,
            Subject: "Numeracy",
            Location: "Building-D07",
            price: 1000,
            image: "Numeracy.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1002,
            Subject: "Literacy",
            Location: "Building-A10",
            price: 1500,
            image: "Literacy.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1003,
            Subject: "Art",
            Location: "Building-E12",
            price: 2000,
            image: "Art.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1004,
            Subject: "Physical education",
            Location: "Building-D01",
            price: 2500,
            image: "Physical education.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1005,
            Subject: "History",
            Location: "Building-C16",
            price: 3000,
            image: "History.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1006,
            Subject: "Design and technology",
            Location: "Building-A05",
            price: 3500,
            image: "Design and technology.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1007,
            Subject: "Geography",
            Location: "Building-B08",
            price: 4000,
            image: "Geography.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1008,
            Subject: "Science",
            Location: "Building-E20",
            price: 4500,
            image: "Science.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1009,
            Subject: "Music",
            Location: "Building-A15",
            price: 5000,
            image: "Music.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
        { id: 1010,
            Subject: "Spanish",
            Location: "Building-B18",
            price: 5500,
            image: "Spanish.png",
            spaces: 5,
            rating: 3,
            quantity: 1,
        },
]